#!/usr/bin/env python3
"""
Generate glove-vectors.js from GloVe 6B 50-dimensional vectors.

Steps:
  1. Download glove.6B.zip from Stanford and extract glove.6B.50d.txt here, OR
     let this script download it automatically (requires ~170 MB download).
  2. Run:  python3 generate-glove.py
  Output: glove-vectors.js  (~3 MB, top 10 000 words, L2-normalised)
"""

import json, math, os, sys, urllib.request, zipfile, io

GLOVE_TXT  = "glove.6B.50d.txt"
OUTPUT_JS  = "glove-vectors.js"
MAX_WORDS  = 10_000
DIMS       = 50
GLOVE_URL  = "https://nlp.stanford.edu/data/glove.6B.zip"


def download_glove():
    print(f"Downloading GloVe from {GLOVE_URL} (~170 MB) …")
    buf = io.BytesIO()
    with urllib.request.urlopen(GLOVE_URL) as r:
        total = int(r.headers.get("Content-Length", 0))
        done  = 0
        while chunk := r.read(1 << 16):
            buf.write(chunk)
            done += len(chunk)
            if total:
                pct = done * 100 // total
                print(f"\r  {pct}% ({done // 1024 // 1024} MB)", end="", flush=True)
    print()
    print("Extracting …")
    with zipfile.ZipFile(buf) as z:
        z.extract(GLOVE_TXT)
    print(f"Extracted {GLOVE_TXT}")


def l2_norm(vec):
    mag = math.sqrt(sum(v * v for v in vec))
    return [v / mag for v in vec] if mag else vec


def main():
    if not os.path.exists(GLOVE_TXT):
        answer = input(f"{GLOVE_TXT} not found. Download automatically? [y/N] ").strip().lower()
        if answer == "y":
            download_glove()
        else:
            print(f"Place {GLOVE_TXT} in this directory and re-run.")
            sys.exit(1)

    words, flat = [], []
    print(f"Reading {GLOVE_TXT} (top {MAX_WORDS} words) …")
    with open(GLOVE_TXT, encoding="utf-8") as f:
        for i, line in enumerate(f):
            if i >= MAX_WORDS:
                break
            parts = line.split()
            if len(parts) != DIMS + 1:
                continue
            vec = l2_norm([float(x) for x in parts[1:]])
            words.append(parts[0])
            flat.extend(round(v, 5) for v in vec)
            if (i + 1) % 2000 == 0:
                print(f"  {i + 1} …")

    print(f"Writing {OUTPUT_JS} …")
    with open(OUTPUT_JS, "w", encoding="utf-8") as f:
        f.write("// Auto-generated by generate-glove.py — do not edit\n")
        f.write(f"// GloVe 6B {DIMS}d · top {len(words)} words · L2-normalised\n")
        f.write("window.GLOVE_WORDS=")
        f.write(json.dumps(words, ensure_ascii=False))
        f.write(";\n")
        f.write(f"window.GLOVE_DIMS={DIMS};\n")
        f.write("window.GLOVE_VECS=new Float32Array(")
        f.write(json.dumps(flat))
        f.write(");\n")

    size = os.path.getsize(OUTPUT_JS) / 1024 / 1024
    print(f"Done — {OUTPUT_JS}  {size:.1f} MB  ({len(words)} words)")


if __name__ == "__main__":
    main()
